sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t iceshop/docker-frontend -f Dockerfile.dev .

script:
  - docker run iceshop/docker-frontend npm run test -- --coverage